#### Pivot Tables
##### A pivot table takes a DataFrame and lets you:

##### Group data by one or more columns (index)

##### Aggregate values (values) using functions like sum, mean, count

##### Optionally create columns from unique values (columns)

In [1]:
import numpy as np
import pandas as pd

In [5]:
data={

    'Date' : pd.date_range('2026-01-01',periods=20),
    'Product' : ['A','B','C','D'] * 5,
    'Region' :['East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South'],
    'Sales':np.random.randint(100,1000,20),
    'Units':np.random.randint(10,100,20),
    'Rep'  : [
        'John','Mary','Bob','Alice','John','Mary','Bob','Alice','John','Mary','Bob','Alice',
        'John','Mary','Bob','Alice','John','Mary','Bob','Alice'
    ]

}
df=pd.DataFrame(data)
df['Months'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q'+df['Date'].dt.quarter.astype(str)

In [6]:
df

         Date Product Region  Sales  Units    Rep   Months Quarter
0  2026-01-01       A   East    312     21   John  January      Q1
1  2026-01-02       B   West    406     21   Mary  January      Q1
2  2026-01-03       C  North    514     80    Bob  January      Q1
3  2026-01-04       D  South    849     72  Alice  January      Q1
4  2026-01-05       A   East    829     82   John  January      Q1
5  2026-01-06       B   West    628     29   Mary  January      Q1
6  2026-01-07       C  North    521     31    Bob  January      Q1
7  2026-01-08       D  South    439     82  Alice  January      Q1
8  2026-01-09       A   East    242     88   John  January      Q1
9  2026-01-10       B   West    527     78   Mary  January      Q1
10 2026-01-11       C  North    513     22    Bob  January      Q1
11 2026-01-12       D  South    839     49  Alice  January      Q1
12 2026-01-13       A   East    176     65   John  January      Q1
13 2026-01-14       B   West    320     44   Mary  January      Q1
14 2026-01-15       C  North    188     71    Bob  January      Q1
15 2026-01-16       D  South    933     89  Alice  January      Q1
16 2026-01-17       A   East    342     27   John  January      Q1
17 2026-01-18       B   West    724     15   Mary  January      Q1
18 2026-01-19       C  North    853     54    Bob  January      Q1
19 2026-01-20       D  South    809     38  Alice  January      Q1

In [7]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')

Product      A      B      C      D
Region
East     380.2    NaN    NaN    NaN
North      NaN    NaN  517.8    NaN
South      NaN    NaN    NaN  773.8
West       NaN  521.0    NaN    NaN

In [8]:
pd.pivot_table(df,values='Units',index='Product',columns='Region')

Region   East  North  South  West
Product
A        56.6    NaN    NaN   NaN
B         NaN    NaN    NaN  37.4
C         NaN   51.6    NaN   NaN
D         NaN    NaN   66.0   NaN

In [9]:
pd.pivot_table(df,values=['Units','Sales'],index='Product',columns='Region')

         Sales                      Units
Region    East  North  South   West  East North South  West
Product
A        380.2    NaN    NaN    NaN  56.6   NaN   NaN   NaN
B          NaN    NaN    NaN  521.0   NaN   NaN   NaN  37.4
C          NaN  517.8    NaN    NaN   NaN  51.6   NaN   NaN
D          NaN    NaN  773.8    NaN   NaN   NaN  66.0   NaN

In [10]:
pd.pivot_table(df,values='Units',index='Product',columns='Region',aggfunc='sum')

Region    East  North  South   West
Product
A        283.0    NaN    NaN    NaN
B          NaN    NaN    NaN  187.0
C          NaN  258.0    NaN    NaN
D          NaN    NaN  330.0    NaN

#### Cross Tabs

In [ ]:
#cross tabulation (crosstab) is a way to compute a frequency table of two (or more) variables.

# It is like a pivot table, but specifically used to count occurrences and show relationships between categorical variables.
#

In [16]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [15]:
pd.crosstab(df['Region'],df['Product']).sum()

Product
A    5
B    5
C    5
D    5
dtype: int64